name: ESP32 BLE Presence Addon
slug: esp32_ble_presence
version: "1.1.0.9"
description: ESP32 BLE presence management
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
startup: "application"
boot: auto
ingress: true
ingress_port: 8100
host_network: true
panel_icon: mdi:bluetooth
panel_title: ESP32 Presence
init: false
