name: ESP32 BLE Presence Addon
slug: esp32_ble_presence
version: "1.0.10"
description: ESP32 BLE presence management
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
ingress: true
ingress_port: 5000
panel_icon: mdi:bluetooth
panel_title: ESP32 Presence
init: false
options:
  mqtt_broker: core-mosquitto
  zigbee_topic: zigbee/presence
  scan_interval_sec: 6
  rssi_threshold: -70
schema:
  mqtt_broker: str
  zigbee_topic: str
  scan_interval_sec: int
  rssi_threshold: int
