name: ESP32 BLE Presence Addon
version: 1.0.0
slug: esp32-presence
arch:
- amd64
- armv7
- aarch64
- armhf
- i386
init: false
boot: auto
host_network: false
panel_icon: mdi:bluetooth
panel_title: ESP32 Presence
ingress: true
webui: http://[HOST]:5000
options:
  mqtt_broker: mqtt://core-mosquitto
  zigbee_topic: zigbee/presence
  scan_interval_sec: 6
  rssi_threshold: -70
schema:
  mqtt_broker: str
  zigbee_topic: str
  scan_interval_sec: int
  rssi_threshold: int