name: Test Addon
description: basically a template
version: 1.0.12
slug: test_addon
init: false
arch:
- amd64
- armv7
- armhf
- aarch64
- i386
panel_icon: "mdi:sprout"
panel_title: Test Addon
ingress: true
ingress_port: 8099
startup: "application"
boot: auto
options:
  mqtt_broker: mqtt://core-mosquitto
  zigbee_topic: zigbee/presence
  scan_interval_sec: 6
  rssi_threshold: -70
schema:
  mqtt_broker: str
  zigbee_topic: str
  scan_interval_sec: int
  rssi_threshold: int

